### ISSUE TITLE
SlayerCult

### ISSUE THREAD

**Issue by SlayerCult** [dotnet/docs.ru-ru#111]
Очень краткая, при этом понятная, ясная и содержательная документация с интерактивными уроками. Очень хотелось бы увидеть полноценный учебник C# выполненный таким образом!

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: 8b514dfb-f00b-8ac3-4027-7a28770f959e
* Version Independent ID: 7db3af08-9406-10da-76a1-1f8db30d1d2d
* Content: [Краткие руководства по C#. Интерактивное руководство по Hello World](https://docs.microsoft.com/ru-ru/dotnet/csharp/quick-starts/hello-world?tutorial-step=7)
* Content Source: [docs/csharp/quick-starts/hello-world.yml](https://github.com/dotnet/docs.ru-ru/blob/live-sxs/docs/csharp/quick-starts/hello-world.yml)
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by gosali** [comment]
Здравствуйте, @SlayerCult ! 

Спасибо за отзыв. 

Мы активно просматриваем комментарии и скоро ответим Вам. 

С наилучшими пожеланиями, 
Международная команда поддержки документации Майкрософт
