### ISSUE TITLE
"A".."Z" или 1..9 Диапазонные значения

### ISSUE THREAD

**Issue by NoNameUserDev** [dotnet/docs.ru-ru#115]
Как же реализовать эти значения?
Напримерь в языке программирования Delphi или Object Pascal такой:
Case x of
2..8: WriteLine('in 2..8');
'2'..'8': WriteLine('in 2..8');
end;
Если прочитали это, Спасибо вам за внимания :) Жду ответа !

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: b9770af4-de82-7034-a56b-c68a6b5c55e5
* Version Independent ID: 6bd64fcc-5c84-e541-12f4-0cdcfe4f5dd2
* Content: [Типы и переменные в C#. Краткий обзор языка C#](https://docs.microsoft.com/ru-ru/dotnet/csharp/tour-of-csharp/types-and-variables)
* Content Source: [docs/csharp/tour-of-csharp/types-and-variables.md](https://github.com/dotnet/docs.ru-ru/blob/live/docs/csharp/tour-of-csharp/types-and-variables.md)
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by gosali** [comment]
Здравствуйте,   @NoNameUserDev !
 
Благодарим Вас за участие.   Наши специалисты могут отвечать только на отзывы по документации.
 
Чтобы оставить отзыв по   продукту, воспользуйтесь кнопкой «Оставить отзыв о   продукте» внизу страницы портала   документации.
  
А по текущему каналу Вы можете   оставлять любые отзывы, связанные с документацией.
 
Мы очень ценим Ваш вклад в   наши статьи.
  
С наилучшими   пожеланиями,
 
Международная команда   поддержки документации Майкрософт
