### ISSUE TITLE
Great

### ISSUE THREAD

**Issue by p1zza** [dotnet/docs.ru-ru#119]
Интересная и полезная вещь, особенно для начала

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: 8b514dfb-f00b-8ac3-4027-7a28770f959e
* Version Independent ID: 7db3af08-9406-10da-76a1-1f8db30d1d2d
* Content: [Краткие руководства по C#. Интерактивное руководство по Hello World](https://docs.microsoft.com/ru-ru/dotnet/csharp/quick-starts/hello-world?tutorial-step=7)
* Content Source: [docs/csharp/quick-starts/hello-world.yml](https://github.com/dotnet/docs.ru-ru/blob/live-sxs/docs/csharp/quick-starts/hello-world.yml)
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by LisandroSu** [comment]
Привет, @p1zza 
 
Ваша обратная связь очень ценится. Мы рады видеть, что ваш опыт работы с нашей документацией соответствует вашим ожиданиям.
Мы призываем вас предоставить ценные отзывы, чтобы мы могли продолжать совершенствовать свой опыт.
 
С уважением,
Международная команда Microsoft DOCS
