### ISSUE TITLE
Разный перевод для Owned Entity Types

### ISSUE THREAD

**Issue by gmatv** [dotnet/docs.ru-ru#123]
В разных местах применяется разный перевод для одного термина: "Owned Entity Types":
https://docs.microsoft.com/ru-ru/ef/core/modeling/owned-entities
https://docs.microsoft.com/ru-ru/dotnet/standard/microservices-architecture/microservice-ddd-cqrs-patterns/implement-value-objects#persist-value-objects-as-owned-entity-types-in-ef-core-20

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: 70b14bbb-dc66-f1a2-8b14-39ef3b4bde1d
* Version Independent ID: 4f0bfce6-eac9-e09e-0d17-08c2842720ac
* Content: [Реализация объектов значений](https://docs.microsoft.com/ru-ru/dotnet/standard/microservices-architecture/microservice-ddd-cqrs-patterns/implement-value-objects)
* Content Source: [docs/standard/microservices-architecture/microservice-ddd-cqrs-patterns/implement-value-objects.md](https://github.com/dotnet/docs.ru-ru/blob/live/docs/standard/microservices-architecture/microservice-ddd-cqrs-patterns/implement-value-objects.md)
* GitHub Login: @CESARDELATORRE
* Microsoft Alias: **wiwagn**

**Comment by LisandroSu** [comment]
Здравствуйте, @gmatv ! 

Спасибо за отзыв. 

Мы активно просматриваем комментарии и скоро ответим Вам. 

С наилучшими пожеланиями, 
Международная команда поддержки документации Майкрософт

**Comment by LisandroSu** [comment]
Здравствуйте, @gmatv !

Спасибо за отзыв.

Мы активно просматриваем комментарии и скоро ответим Вам.

С наилучшими пожеланиями,
Международная команда поддержки документации Майкрософт

**Comment by gosali** [comment]
Здравствуйте, @gmatv !

Спасибо за отзыв.

Мы активно просматриваем комментарии и скоро ответим Вам.

С наилучшими пожеланиями,
Международная команда поддержки документации Майкрософт

**Comment by LisandroSu** [comment]
Здравствуйте, @gmatv !  

Спасибо за отзыв. 

Наши лингвисты рассмотрели Ваши предложения и приняли их. Мы внедрили Ваши правки в обновленные статьи на сайте документации, опубликованные на следующих страницах: https://docs.microsoft.com/ru-ru/ef/core/modeling/owned-entities.  

Мы очень ценим Ваш вклад в наши статьи и будем рады получить другие полезные отзывы. 

С наилучшими пожеланиями, 
Международная команда поддержки документации Майкрософт

**Comment by gmatv** [comment]
Прошу прощения, что был недостаточно точен:

1. https://docs.microsoft.com/ru-ru/ef/core/modeling/owned-entities

Оригинал: Owned Entity Types
Перевод: Собственные типы сущностей

2. https://docs.microsoft.com/ru-ru/dotnet/standard/microservices-architecture/microservice-ddd-cqrs-patterns/implement-value-objects#persist-value-objects-as-owned-entity-types-in-ef-core-20

Оригинал: Persist value objects as **owned entity types** in EF Core 2.0
Перевод: Хранение объектов значений в виде **принадлежащих типов сущностей** в EF Core 2.0
