### ISSUE TITLE
Ошибка на странице с описанием модификаторов доступа (private и private protected)

### ISSUE THREAD

**Issue by miksarus** [dotnet/docs.ru-ru#135]
Не корректно указано описание модификаторов доступа на странице. Private - модификатор доступа относящийся только к членам и к типу применяться не может. То же самое касается и private protected.

**Comment by LisandroSu** [comment]
Здравствуйте, @miksarus !

Благодарим Вас за предоставленный комментарий. Комментарии помогают нам постоянно улучшать портал docs.microsoft.com. Однако нам необходимы дополнительные сведения, чтобы проанализировать Ваш отзыв. Не могли бы Вы дать более подробную информацию и пояснить свой комментарий?

С уважением,
Международная команда Microsoft DOCS

**Comment by LisandroSu** [comment]
Здравствуйте, @miksarus ! 

 Спасибо за отзыв. 

 Мы активно просматриваем комментарии и скоро ответим Вам. 

 С наилучшими пожеланиями, 
Международная команда поддержки документации Майкрософт

**Comment by LisandroSu** [comment]
Issue moved to [dotnet/docs #8077](https://github.com/dotnet/docs/issues/8077) via [**ZenHub**](https://www.zenhub.com/)

**Comment by LisandroSu** [comment]
Здравствуйте, @miksarus ! 

Благодарим Вас за участие. Ваш отзыв связан с исходной документацией. 

Поэтому мы переносим Вашу заявку в репозиторий по английскому языку. Ее состояние можно просмотреть здесь: https://github.com/dotnet/docs/issues/8077. 

Мы очень ценим Ваш вклад в наши статьи.  

С наилучшими пожеланиями, 
Международная команда поддержки документации Майкрософт
