### ISSUE TITLE
This is an issue

### ISSUE THREAD

**Issue by Volodya262** [dotnet/docs.ru-ru#149]
Плохой перевод

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: 9966701f-da61-4a58-bdd7-8108a50fddab
* Version Independent ID: fb41c342-60a1-0064-7340-717082136905
* Content: [Шаблон ликвидации](https://docs.microsoft.com/ru-ru/dotnet/standard/design-guidelines/dispose-pattern#feedback)
* Content Source: [docs/standard/design-guidelines/dispose-pattern.md](https://github.com/dotnet/docs.ru-ru/blob/live/docs/standard/design-guidelines/dispose-pattern.md)
* Product: **dotnet**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by LisandroSu** [comment]
Здравствуйте, @Volodya262 ! 
Спасибо за отзыв. Рассматриваемая страница переведена с использованием машинного перевода, который не всегда идеально понятен. Недавно мы добавили справа на странице функцию «Прочитать на английском», которая позволяет переключиться на английскую версию, не меняя настройки языка. 
С наилучшими пожеланиями, 
Международная команда поддержки документации Майкрософт
