### ISSUE TITLE
Error in text in Russian tutorial

### ISSUE THREAD

**Issue by CeciAc** [dotnet/docs.ru-ru#150]
I'm copy-pasting this manually from https://github.com/MicrosoftDocs/feedback/issues/849

> 
> Hello we received the issue below on try .net repo. 
> Could you please have a look ? dotnet/try#140  
> https://docs.microsoft.com/ru-ru/dotnet/csharp/quick-starts/list-collection?tutorial-step=3 Text:  
> 
> Если он имеет значение 1, элемент не найден  Correct version: Если он имеет значение -1, элемент не найден

**Comment by CeciAc** [comment]
@JasonCard 
This was fixed as follows:
SRC: If it is -1, the item was not found.
TGT: Если он имеет значение 1, элемент не найден.
CORRECT: Если он имеет значение 1, элемент не найден.

Kind regards,
Microsoft DOCS International Team

**Comment by JasonCard** [comment]
Confirmed live is fixed with "-" as: Если он имеет значение -1, элемент не найден.
