### ISSUE TITLE
Expected "using" directives

### ISSUE THREAD

**Issue by veotani** [dotnet/docs.ru-ru#153]
In the paragraph "Define data and model paths" there is the following phrase: "To make the preceding code compile, add the following using directives at the top of the Program.cs file:". Expected some using directives, but got this: "var metrics = mlContext.Regression.Evaluate(predictions, "Label", "Score");". Feels like it shouldn't be here.

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: a30b3ff5-b5e6-ff02-6f60-b5cef6f34666
* Version Independent ID: fdf962e2-620e-d9ad-5057-5f96f52dc60f
* Content: [Использование ML.NET для прогнозирования платы за проезд в такси в Нью-Йорке (регрессия)](https://docs.microsoft.com/ru-ru/dotnet/machine-learning/tutorials/taxi-fare)
* Content Source: [docs/machine-learning/tutorials/taxi-fare.md](https://github.com/dotnet/docs.ru-ru/blob/live/docs/machine-learning/tutorials/taxi-fare.md)
* Product: **dotnet-ml**
* GitHub Login: @aditidugar
* Microsoft Alias: **johalex**

**Comment by veotani** [comment]
If i am not mistaken, the "using Microsoft.ML.Runtime.Data;" as the code sample should be there.

**Comment by CeciAc** [comment]
Issue moved to [dotnet/docs #8995](https://github.com/dotnet/docs/issues/8995) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @veotani 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/dotnet/docs/issues/8995.

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team

**Comment by mairaw** [comment]
@CeciAc I'm reopening the issue here since this is due to loc version not being up-to-date. 

@veotani please look at the latest English version for now: https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/taxi-fare

**Comment by veotani** [comment]
@CeciAc as I understand there is a difference between russian version of the article in english and english article. Didn't know about it. 

The problem still exists but now i am able to point on it in Russian version:

> Чтобы этот код компилировался, добавьте следующие директивы using вверху файла Program.
> `var metrics = mlContext.Regression.Evaluate(predictions, "Label", "Score");`

Must be replaced with:
> Чтобы этот код компилировался, добавьте следующие директивы using вверху файла Program.
> `using Microsoft.ML.Runtime.Data;`

Feel free to close this issue if the localisation is still in progress and this is not the final version of the article.

Thank you for answering!

**Comment by mairaw** [comment]
Yes @veotani. When you use the switch to see the English version on the ru-ru address, it shows the original text that was translated. If you switch to en-us, you see the latest version of the article.

**Comment by CeciAc** [comment]
Hello, @veotani 
Thank you for your feedback.
 
Our linguistic team reviewed your linguist suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/ru-ru/dotnet/machine-learning/tutorials/taxi-fare. 

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.

Kind regards,
Microsoft DOCS International Team
