### ISSUE TITLE
Please, modify Dictionary<TKey,TValue> class description in Russian language

### ISSUE THREAD

**Issue by kkostenkov** [dotnet/docs.ru-ru#158]
In Russian the description of  Dictionary&lt;TKey,TValue&gt; is written as "Предоставляет коллекцию пар «ключ-значение», которые упорядочены по ключу." This is translated as "Represents a collection of key/value pairs that are ordered based on the key."
To correct this phrase please replace word "упорядочены" with "хранятся" which could be translated as "... that are stored based on the key"

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: ee0b88ff-d651-fd2f-a6e4-acfa1089b1f2
* Version Independent ID: bc5056d9-27ed-f1ce-bc7a-6e61121a578d
* Content: [Коллекции (C#)](https://docs.microsoft.com/ru-ru/dotnet/csharp/programming-guide/concepts/collections)
* Content Source: [docs/csharp/programming-guide/concepts/collections.md](https://github.com/dotnet/docs.ru-ru/blob/live/docs/csharp/programming-guide/concepts/collections.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by CeciAc** [comment]
Hello, @kkostenkov 
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Здравствуйте, @kkostenkov 
 Благодарим за Ваши лингвистические правки.  
К сожалению, рассмотрев Ваш отзыв, наши лингвисты не смогли принять его, так как он не соответствует в полной мере нашим критериям по следующим причинам: [Фраза “хранятся по ключу” нелогична и звучит непонятно, а “упорядочены” соответствует оригиналу “organized”.] 
Мы очень ценим Ваш вклад в наши статьи и будем рады получить другие полезные отзывы.  
С наилучшими пожеланиями, 
Международная команда поддержки документации Майкрософт
