### ISSUE TITLE
Error in text

### ISSUE THREAD

**Issue by 4174** [dotnet/docs.ru-ru#160]
"Однако поля остаются незназначенными..." - ошибка в слове "не назначенными".

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: 7c1a2eef-19ac-f7a3-a512-df2729412a53
* Version Independent ID: 1f413a9f-7129-df5c-e8fa-13647cc1caeb
* Content: [Руководство по программированию на C#. Использование структур](https://docs.microsoft.com/ru-ru/dotnet/csharp/programming-guide/classes-and-structs/using-structs)
* Content Source: [docs/csharp/programming-guide/classes-and-structs/using-structs.md](https://github.com/dotnet/docs.ru-ru/blob/live/docs/csharp/programming-guide/classes-and-structs/using-structs.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by CeciAc** [comment]
Здравствуйте, @4174 
Спасибо за отзыв. 
Наши лингвисты рассмотрели Ваши предложения и приняли их. Мы внедрили Ваши правки в обновленные статьи на сайте документации, опубликованные на следующих страницах: https://docs.microsoft.com/ru-ru/dotnet/csharp/programming-guide/classes-and-structs/using-structs.  
Мы очень ценим Ваш вклад в наши статьи и будем рады получить другие полезные отзывы. 
С наилучшими пожеланиями, 
Международная команда поддержки документации Майкрософт
