### ISSUE TITLE
Нет примера вызова из C#

### ISSUE THREAD

**Issue by vasil-1603** [dotnet/docs.ru-ru#169]
Очень не хватает примера возможных вызовов из C# !

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: 678eaef3-eec4-dc52-1234-37e220f84682
* Version Independent ID: 38b09163-65d8-4d6c-1394-401e080ed6f0
* Content: [Маршалинг данных при вызове неуправляемого кода](https://docs.microsoft.com/ru-ru/dotnet/framework/interop/marshaling-data-with-platform-invoke)
* Content Source: [docs/framework/interop/marshaling-data-with-platform-invoke.md](https://github.com/dotnet/docs.ru-ru/blob/live/docs/framework/interop/marshaling-data-with-platform-invoke.md)
* Product: **dotnet-framework**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by LisandroSu** [comment]
Issue moved to [dotnet/docs #10308](https://github.com/dotnet/docs/issues/10308) via [**ZenHub**](https://www.zenhub.com/)

**Comment by LisandroSu** [comment]
Здравствуйте, @vasil-1603 ! 

Благодарим Вас за участие. Ваш отзыв связан с исходной документацией. 
Поэтому мы переносим Вашу заявку в репозиторий по английскому языку. Ее состояние можно просмотреть здесь: https://github.com/dotnet/docs/issues/10308. 

Мы очень ценим Ваш вклад в наши статьи.  
С наилучшими пожеланиями, 
Международная команда поддержки документации Майкрософт
