### ISSUE TITLE
Тег <list> не работает!

### ISSUE THREAD

**Issue by vasil-1603** [dotnet/docs.ru-ru#170]
Тег &lt;list&gt; не работает!

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: 40ad53e4-4786-d1a1-5f8a-2a8b914ebb37
* Version Independent ID: df94f227-fd86-0fad-e5fe-d0053d9ed321
* Content: [&lt;list&gt; — Руководство по программированию на C#](https://docs.microsoft.com/ru-ru/dotnet/csharp/programming-guide/xmldoc/list)
* Content Source: [docs/csharp/programming-guide/xmldoc/list.md](https://github.com/dotnet/docs.ru-ru/blob/live/docs/csharp/programming-guide/xmldoc/list.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by CeciAc** [comment]
Здравствуйте, @vasil-1603 
Благодарим Вас за участие. Наши специалисты могут отвечать только на отзывы по документации. 
Чтобы оставить отзыв по продукту, воспользуйтесь кнопкой «Оставить отзыв о продукте» внизу страницы портала документации. 
А по текущему каналу Вы можете оставлять любые отзывы, связанные с документацией. 
Мы очень ценим Ваш вклад в наши статьи.  
С наилучшими пожеланиями, 
Международная команда поддержки документации Майкрософт
