### ISSUE TITLE
Can you rewrite the article?

### ISSUE THREAD

**Issue by x13xxxswatxxx** [dotnet/docs.ru-ru#176]
For me personally, the article seemed complicated.
5 times (2 days), already tried to start over and just got more confused.
The beginning is more or less clear, but then comes the use of event, EventHandler &lt;class&gt;, creating classes for it, using lambda expressions for add, remove, as if we work with them every day.
why internal to create an extension?
It is not clear which class to insert search into.
where did lister come from and how to apply at all.

Лично для меня, статья показалась сложной.
5 раз (2-х дней),  уже пробовал начинать сначала и только больше запутался.
Начало более менее понятно, но далее идёт применение event, EventHandler&lt;class&gt;, создание классов под него, применение лямбда выражений для add, remove,  как будто мы работаем с ними каждый день.
зачем internal, чтобы создать расширение?
Непонятно в какой класс нужно вставлять search.
откуда взяли lister и как вообще применить.

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: 90b37f1a-cd59-d9e5-067b-30ea5f26e5cc
* Version Independent ID: d2078536-1ee3-5b60-3872-f2635d245cc2
* Content: [Стандартные шаблоны событий .NET](https://docs.microsoft.com/ru-ru/dotnet/csharp/event-pattern#feedback)
* Content Source: [docs/csharp/event-pattern.md](https://github.com/dotnet/docs.ru-ru/blob/live/docs/csharp/event-pattern.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by CeciAc** [comment]
Issue moved to [dotnet/docs #10852](https://github.com/dotnet/docs/issues/10852) via [**ZenHub**](https://www.zenhub.com/)
