### ISSUE TITLE
Most of the code in article is absent

### ISSUE THREAD

**Issue by Skybladev2** [dotnet/docs.ru-ru#180]
Article is unusable, because I don't see most of the code.

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: c8e22825-c4ee-5a36-f911-8ad456970ecc
* Version Independent ID: ad0bf640-7dfc-1184-077c-358bb14277a7
* Content: [Использование ML.NET для анализа тональности методом двоичной классификации](https://docs.microsoft.com/ru-ru/dotnet/machine-learning/tutorials/sentiment-analysis#feedback)
* Content Source: [docs/machine-learning/tutorials/sentiment-analysis.md](https://github.com/dotnet/docs.ru-ru/blob/live/docs/machine-learning/tutorials/sentiment-analysis.md)
* Product: **dotnet-ml**
* GitHub Login: @JRAlexander
* Microsoft Alias: **johalex**

**Comment by CeciAc** [comment]
Hello, @Skybladev2 

Thank for your contribution. We are currently reviewing it. We will communicate the decision taken accordingly. 
 
Thanks for your time and support on this.

Kind regards,

Microsoft C&E Localization Team

**Comment by CeciAc** [comment]
Hello, @Skybladev2

Thank you for your feedback.
 
Our engineer team reviewed your suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/ru-ru/dotnet/machine-learning/tutorials/sentiment-analysis#feedback

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.

Kind regards,
Microsoft DOCS International Team
