### ISSUE TITLE
команда dotnet new console

### ISSUE THREAD

**Issue by CracedDown** [dotnet/docs.ru-ru#186]
здравствуйте , у меня линукс. Я не понимаю что с "dotnet new console". выводит ошибку:  If 'dotnet' is not a typo you can use command-not-found to lookup the package that contains it, like this:
    cnf dotnet   . что мне делать???

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: 8cc2e9c2-f333-f6a1-064e-790d950b684c
* Version Independent ID: 25a4c9b9-2808-e296-df03-5837000dcbad
* Content: [Начало работы с C# и Visual Studio Code](https://docs.microsoft.com/ru-ru/dotnet/core/tutorials/with-visual-studio-code#feedback)
* Content Source: [docs/core/tutorials/with-visual-studio-code.md](https://github.com/dotnet/docs.ru-ru/blob/live/docs/core/tutorials/with-visual-studio-code.md)
* Product: **dotnet-core**
* GitHub Login: @kendrahavens
* Microsoft Alias: **mairaw**

**Comment by CeciAc** [comment]
Здравствуйте, @CracedDown 
Благодарим Вас за участие. Наши специалисты могут отвечать только на отзывы по документации. 
Чтобы оставить отзыв по продукту, воспользуйтесь кнопкой «Оставить отзыв о продукте» внизу страницы портала документации. 
А по текущему каналу Вы можете оставлять любые отзывы, связанные с документацией. 
Мы очень ценим Ваш вклад в наши статьи.  
С наилучшими пожеланиями, 
Международная команда поддержки документации Майкрософт
