### ISSUE TITLE
Translation improvement

### ISSUE THREAD

**Issue by kudriako** [dotnet/docs.ru-ru#191]
Instead of the title
'Получение обновлений ходы выполнения и добавочных результатов'
it is better to use
'Получение обновлений ход**а** выполнения и **дополнительных** результатов'
The same:
добавочных результатов -> дополнительных результатов
добавочные результаты -> дополнительные результаты

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: a2f0335f-97ae-fa82-1803-86563d2df020
* Version Independent ID: 67e2001c-ecfa-9e9c-6f51-8301c8a107d2
* Content: [Обзор асинхронной модели, основанной на событиях](https://docs.microsoft.com/ru-ru/dotnet/standard/asynchronous-programming-patterns/event-based-asynchronous-pattern-overview)
* Content Source: [docs/standard/asynchronous-programming-patterns/event-based-asynchronous-pattern-overview.md](https://github.com/dotnet/docs.ru-ru/blob/live/docs/standard/asynchronous-programming-patterns/event-based-asynchronous-pattern-overview.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by CeciAc** [comment]
Hello, @kudriako 
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @kudriako 
 
Thank you for your feedback.
 
Our linguistic team reviewed your linguist suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages XXX. 

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.
	
Kind regards,
Microsoft DOCS International Team
