### ISSUE TITLE
4 и 6 строка

### ISSUE THREAD

**Issue by landbool** [dotnet/docs.ru-ru#195]
Не могу разобраться в 4 и 6 строке на 6 шаге,но в 6 строке я +- что-то понял,а вот 4 строка вообще 0 понимания.

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: 77dec100-463d-f684-03b6-25f511d1d18f
* Version Independent ID: 27921da6-71b0-6dfc-2824-c84844152d8e
* Content: [Ветви и циклы. Интерактивное вводное руководство по C#](https://docs.microsoft.com/ru-ru/dotnet/csharp/tutorials/intro-to-csharp/branches-and-loops?tutorial-step=7#feedback)
* Content Source: [docs/csharp/tutorials/intro-to-csharp/branches-and-loops.yml](https://github.com/dotnet/docs.ru-ru/blob/live-sxs/docs/csharp/tutorials/intro-to-csharp/branches-and-loops.yml)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by CeciAc** [comment]
Здравствуйте, @landbool 
Благодарим Вас за участие. Наши специалисты могут отвечать только на отзывы по документации. 
Чтобы оставить отзыв по продукту, воспользуйтесь кнопкой «Оставить отзыв о продукте» внизу страницы портала документации. 
А по текущему каналу Вы можете оставлять любые отзывы, связанные с документацией. 
Мы очень ценим Ваш вклад в наши статьи.  
С наилучшими пожеланиями, 
Международная команда поддержки документации Майкрософт
