### ISSUE TITLE
Ошибка перевода

### ISSUE THREAD

**Issue by green16** [dotnet/docs.ru-ru#199]
Оригинал: Наиболее основных частей любой программы на F# являются функции упорядочены модули.
Следует перевести: Самые основные части любой программы на F# являются функции, упорядоченные в модули
Далее
Оригинал: Функции выполнения на входные данные для создания выходных значений, и они группируются по модули, которые являются основным способом сгруппировать объекты в F#
Следует перевести: Функции работают с входными данными для создания выходных значений и группируются в модули, которые являются основным способом сгруппировать объекты в F#

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: 89bef555-3de1-5d81-c02b-2ac8c049423b
* Version Independent ID: eb13ad9e-2c95-979b-6d6e-13d29653c6ba
* Content: [Обзор языка F#](https://docs.microsoft.com/ru-ru/dotnet/fsharp/tour#feedback)
* Content Source: [docs/fsharp/tour.md](https://github.com/dotnet/docs.ru-ru/blob/live/docs/fsharp/tour.md)
* Product: **dotnet-fsharp**
* GitHub Login: @cartermp
* Microsoft Alias: **phcart**

**Comment by CeciAc** [comment]
Здравствуйте, @green16 !  

 Спасибо за отзыв.  

 Мы активно просматриваем комментарии и скоро ответим Вам.  

 С наилучшими пожеланиями,  

Международная команда поддержки документации Майкрософт

**Comment by CeciAc** [comment]
Здравствуйте, @green16 
Спасибо за отзыв. Рассматриваемая страница переведена с использованием машинного перевода, который не всегда идеально понятен. Недавно мы добавили справа на странице функцию «Прочитать на английском», которая позволяет переключиться на английскую версию, не меняя настройки языка. 
С наилучшими пожеланиями, 
Международная команда поддержки документации Майкрософт
