### ISSUE TITLE
Непонятный перевод

### ISSUE THREAD

**Issue by sokrata** [dotnet/docs.ru-ru#205]
Перевод не дает понять что за числа в начале строки:
The numbers returned by these methods are in font design units, so they are independent of the size and units of a particular Font object.
Должно быть что-то подобное:
Значения, возвращаемые этими методами, заданы в единицах шрифта, поэтому они не зависят от размера и единиц измерений конкретного объекта Font.

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: e3f6c7d6-a5a5-0cfa-45ed-23e99e236b6e
* Version Independent ID: cc28c628-46d6-520a-d5e5-c47682c59bc6
* Content: [Практическое руководство. Получение метрик шрифтов](https://docs.microsoft.com/ru-ru/dotnet/framework/winforms/advanced/how-to-obtain-font-metrics#feedback)
* Content Source: [docs/framework/winforms/advanced/how-to-obtain-font-metrics.md](https://github.com/dotnet/docs.ru-ru/blob/live/docs/framework/winforms/advanced/how-to-obtain-font-metrics.md)
* Product: **dotnet-framework**
* Technology: **dotnet-winforms**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by CeciAc** [comment]
Issue moved to [dotnet/docs #12861](https://github.com/dotnet/docs/issues/12861) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Здравствуйте, @sokrata 
Благодарим Вас за участие. Ваш отзыв связан с исходной документацией. 
Поэтому мы переносим Вашу заявку в репозиторий по английскому языку. Ее состояние можно просмотреть здесь: https://github.com/dotnet/docs/issues/12861
Мы очень ценим Ваш вклад в наши статьи.  
С наилучшими пожеланиями, 
Международная команда поддержки документации Майкрософт

**Comment by CeciAc** [comment]
Здравствуйте, @sokrata 
 Спасибо за отзыв. 
 Мы активно просматриваем комментарии и скоро ответим Вам. 
 С наилучшими пожеланиями, 
Международная команда поддержки документации Майкрософт

**Comment by lichasu** [comment]
Здравствуйте, @sokrata !  
Спасибо за отзыв. 
Наши лингвисты рассмотрели Ваши предложения и приняли их. 
Мы очень ценим Ваш вклад в наши статьи и будем рады получить другие полезные отзывы. 
С наилучшими пожеланиями, 
Международная команда поддержки документации Майкрософт
