### ISSUE TITLE
Перевод ключевого слова в оглавлении

### ISSUE THREAD

**Issue by fireton** [dotnet/docs.ru-ru#218]
В оглавлении (слева) ключевое слово where переведено как «где». Что неправильно, это же ключевое слово.

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: 74dfcde5-aa2b-1128-fa29-f198a6e437b7
* Version Independent ID: 59aeccf5-364c-77a8-88dc-cb529b76aebc
* Content: [Справочник по C#. Предложение where (ограничение универсального типа)](https://docs.microsoft.com/ru-ru/dotnet/csharp/language-reference/keywords/where-generic-type-constraint#feedback)
* Content Source: [docs/csharp/language-reference/keywords/where-generic-type-constraint.md](https://github.com/dotnet/docs.ru-ru/blob/live/docs/csharp/language-reference/keywords/where-generic-type-constraint.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by srvbpigh** [comment]
Hello, @fireton
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by fireton** [comment]
I want to clarify. The keyword "where" was translated into Russian in the table of content.

**Comment by CeciAc** [comment]
Здравствуйте, @fireton 
Спасибо за отзыв. 
Наши лингвисты рассмотрели Ваши предложения и приняли их. Мы внедрили Ваши правки в обновленные статьи на сайте документации, опубликованные на следующих страницах: https://docs.microsoft.com/ru-ru/dotnet/csharp/language-reference/keywords/where-generic-type-constraint#feedback
Мы очень ценим Ваш вклад в наши статьи и будем рады получить другие полезные отзывы. 
С наилучшими пожеланиями, 
Международная команда поддержки документации Майкрософт
