### ISSUE TITLE
Возможно тут ошибка?

### ISSUE THREAD

**Issue by AleksTret** [dotnet/docs.ru-ru#226]
В предложении из статьи возможно есть ошибка. В тексте должно быть написано "ковариантым".

Универсальные интерфейсы могут наследоваться от неуниверсальных интерфейсов, если универсальный интерфейс является контравариантным (то есть использует только в качестве возвращаемого значения только свой параметр типа).

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: be0a00a9-fd5d-3aae-9788-d6b324f17599
* Version Independent ID: d54ecf19-fccb-3d6b-d990-81529acf44c3
* Content: [Руководство по программированию на C#. Универсальные интерфейсы](https://docs.microsoft.com/ru-ru/dotnet/csharp/programming-guide/generics/generic-interfaces#feedback)
* Content Source: [docs/csharp/programming-guide/generics/generic-interfaces.md](https://github.com/dotnet/docs.ru-ru/blob/live/docs/csharp/programming-guide/generics/generic-interfaces.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by srvbpigh** [comment]
Hello, @AleksTret
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Здравствуйте, @AleksTret 
Спасибо за отзыв. 
Наши лингвисты рассмотрели Ваши предложения и приняли их. Мы внедрили Ваши правки в обновленные статьи на сайте документации, опубликованные на следующих страницах: https://docs.microsoft.com/ru-ru/dotnet/csharp/programming-guide/generics/generic-interfaces#feedback
Мы очень ценим Ваш вклад в наши статьи и будем рады получить другие полезные отзывы. 
С наилучшими пожеланиями, 
Международная команда поддержки документации Майкрософт
