### ISSUE TITLE
Ошибка в документации

### ISSUE THREAD

**Issue by sungam3r** [dotnet/docs.ru-ru#228]
Если у приложения есть конкретные причины, по котором оно должно использовать ранние версии пакета SDK или среды выполнения, вы можете безопасно удалить старые версии.

Нужно заменить на "Если у приложения нет конкретных причин, по которым..."

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: b4ca18b0-5533-f5b9-2eb4-9853a4fa61ed
* Version Independent ID: a12b8b5c-a3af-d1c5-a27c-39e9d390dff2
* Content: [Удаление среды выполнения .NET Core и пакета SDK - .NET Core](https://docs.microsoft.com/ru-ru/dotnet/core/versions/remove-runtime-sdk-versions?tabs=macos)
* Content Source: [docs/core/versions/remove-runtime-sdk-versions.md](https://github.com/dotnet/docs.ru-ru/blob/live/docs/core/versions/remove-runtime-sdk-versions.md)
* Product: **dotnet-core**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by srvbpigh** [comment]
Hello, @sungam3r
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Здравствуйте, @sungam3r 
Спасибо за отзыв. 
Наши лингвисты рассмотрели Ваши предложения и приняли их. Мы внедрили Ваши правки в обновленные статьи на сайте документации, опубликованные на следующих страницах: https://docs.microsoft.com/ru-ru/dotnet/core/versions/remove-runtime-sdk-versions?tabs=macos
Мы очень ценим Ваш вклад в наши статьи и будем рады получить другие полезные отзывы. 
С наилучшими пожеланиями, 
Международная команда поддержки документации Майкрософт
