### ISSUE TITLE
Опечатка

### ISSUE THREAD

**Issue by ProgrammerForeve** [dotnet/docs.ru-ru#233]
...которые по первому тесту набрали больше 90 баллов, а по второму[по четвертому] — меньше 80 баллов...
или же
where student.Scores[0] &gt; 90 && student.Scores[1] &lt; 80

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: 91094f7e-18ba-59d2-161c-8d354fff9d99
* Version Independent ID: 2139185a-2755-5ce3-e943-665065665e39
* Content: [Пошаговое руководство. Написание запросов на C# (LINQ)](https://docs.microsoft.com/ru-ru/dotnet/csharp/programming-guide/concepts/linq/walkthrough-writing-queries-linq#feedback)
* Content Source: [docs/csharp/programming-guide/concepts/linq/walkthrough-writing-queries-linq.md](https://github.com/dotnet/docs.ru-ru/blob/live/docs/csharp/programming-guide/concepts/linq/walkthrough-writing-queries-linq.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by srvbpigh** [comment]
Hello, @ProgrammerForeve
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Здравствуйте, @ProgrammerForeve 
Спасибо за отзыв. 
Наши лингвисты рассмотрели Ваши предложения и приняли их. Мы внедрили Ваши правки в обновленные статьи на сайте документации, опубликованные на следующих страницах: https://docs.microsoft.com/ru-ru/dotnet/csharp/programming-guide/concepts/linq/walkthrough-writing-queries-linq#feedback
Мы очень ценим Ваш вклад в наши статьи и будем рады получить другие полезные отзывы. 
С наилучшими пожеланиями, 
Международная команда поддержки документации Майкрософт
