### ISSUE TITLE
Article has some translation errors

### ISSUE THREAD

**Issue by Kychanov-sa** [dotnet/docs.ru-ru#239]
You should not translate following terms:
"всфам" is not correct and should be replaces with original WSFAM.
In attributes table leave all left column untranslated because it is a names of attributes not a regular words.
Thanks.
---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: 5554abc7-a864-4357-619a-e43d19e742a8
* Version Independent ID: 9224fbd3-e2fb-9be1-e993-cf2d775e3856
* Content: [&lt;wsFederation&gt;](https://docs.microsoft.com/ru-ru/dotnet/framework/configure-apps/file-schema/windows-identity-foundation/wsfederation)
* Content Source: [docs/framework/configure-apps/file-schema/windows-identity-foundation/wsfederation.md](https://github.com/dotnet/docs.ru-ru/blob/live/docs/framework/configure-apps/file-schema/windows-identity-foundation/wsfederation.md)
* Product: **dotnet-framework**
* GitHub Login: @BrucePerlerMS
* Microsoft Alias: **dotnetcontent**

**Comment by srvbpigh** [comment]
Hello, @Kychanov-sa
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @Kychanov-sa 
 
Thank you for your feedback.
 
Our linguistic team reviewed your linguist suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/ru-ru/dotnet/framework/configure-apps/file-schema/windows-identity-foundation/wsfederation

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.
	
Kind regards,
Microsoft DOCS International Team
