### ISSUE TITLE
Пример не раскрывает сути "private set;"

### ISSUE THREAD

**Issue by vctrro** [dotnet/docs.ru-ru#248]
В этом примере нет никакой разницы между { get; } и { get; private set; }

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: d549e670-9c25-f742-f146-699ba15e39e5
* Version Independent ID: 88fce03f-2ce8-0dd6-ae04-4676fcbb864d
* Content: [Практическое руководство. Реализация облегченного класса с автоматически реализуемыми свойствами (руководство по программированию на C#)](https://docs.microsoft.com/ru-ru/dotnet/csharp/programming-guide/classes-and-structs/how-to-implement-a-lightweight-class-with-auto-implemented-properties#feedback)
* Content Source: [docs/csharp/programming-guide/classes-and-structs/how-to-implement-a-lightweight-class-with-auto-implemented-properties.md](https://github.com/dotnet/docs.ru-ru/blob/live/docs/csharp/programming-guide/classes-and-structs/how-to-implement-a-lightweight-class-with-auto-implemented-properties.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by srvbpigh** [comment]
Hello, @vctrro
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by ticianaciminari** [comment]
Issue moved to [dotnet/docs #16807](https://github.com/dotnet/docs/issues/16807) via [**ZenHub**](https://www.zenhub.com/)

**Comment by ticianaciminari** [comment]
Здравствуйте, @vctrro!

Благодарим Вас за участие. Ваш отзыв связан с исходной документацией.  

Поэтому мы переносим Вашу заявку в репозиторий по английскому языку. Ее состояние можно просмотреть здесь: https://github.com/dotnet/docs/issues/16807.  

Мы очень ценим Ваш вклад в наши статьи.   

С наилучшими пожеланиями,  

Международная команда поддержки документации Майкрософт
