### ISSUE TITLE
Unnecessary machine translation of class names

### ISSUE THREAD

**Issue by darestov** [dotnet/docs.ru-ru#254]
Just look at this:

![image](https://user-images.githubusercontent.com/5158873/74511298-c323ce80-4f16-11ea-8a6c-c93dbd1ed953.png)
And this:
![image](https://user-images.githubusercontent.com/5158873/74511798-ddaa7780-4f17-11ea-90fa-bce46966bcd8.png)

(taken from https://docs.microsoft.com/ru-ru/dotnet/standard/serialization/system-text-json-migrate-from-newtonsoft-how-to)
In green, there is a correct piece. JsonSerializer is a class name, it is not translated (and shouldn't be).
In red are unneeded "translations" of JsonDocument and JsonElement. In fact it is not even a translation, it's just transliteration - an English word with English pronunciation written in cyrillic letters with similar sounding. Such things as class names and other program identifiers **do not need to be translated at all.**

Please, get rid of this. Eyes of any Russian-speaking person start bleeding when he sees it.

**Comment by srvbpigh** [comment]
Hello, @darestov
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by ticianaciminari** [comment]
Hello @darestov:

Thank you for your contribution. 

Contributions on translation problems against machine translated content are currently not accepted. 

We value your feedback and suggestions on human translated content, which is used to train the machine translation engines, so over time, your contributions will improve the quality of both human and machine translations. 

Human translated topics can be distinguished from machine translated topics by the ms.translationtype metadata value “HT” (versus “MT” for machine translated) in the header of each content file. 

Many thanks for your support. 

Microsoft DOCS Global Experience Team
