### ISSUE TITLE
Rewrite GenerateAnswer() method

### ISSUE THREAD

**Issue by musinit** [dotnet/docs.ru-ru#260]
It would be nice to rewrite GenerateAnswer() method with new C#8 switch statement (with =&gt; instead of case)

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: b991cba9-efd4-68ae-283a-b575054b4907
* Version Independent ID: 793f790b-e2aa-e292-b12b-f4ba9763f172
* Content: [Разработка с использованием ссылочных типов, допускающих значение null](https://docs.microsoft.com/ru-ru/dotnet/csharp/tutorials/nullable-reference-types#feedback)
* Content Source: [docs/csharp/tutorials/nullable-reference-types.md](https://github.com/dotnet/docs.ru-ru/blob/live/docs/csharp/tutorials/nullable-reference-types.md)
* Product: **dotnet-csharp**
* Technology: **csharp-null-safety**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by srvbpigh** [comment]
Hello, @musinit
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by ticianaciminari** [comment]
Hello, @musinit,

Your contribution is much appreciated. Our team can only answer feedback related to the documentation. 

Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page. 

If you have any feedback related to the documentation, please feel free to log it through this channel. 

We truly appreciate your contribution to our articles.  

Kind regards, 

Microsoft DOCS International Team
