### ISSUE TITLE
No samples for culture ru-ru

### ISSUE THREAD

**Issue by palicpiotr** [dotnet/docs.ru-ru#261]
Hello, 

[**This**](https://docs.microsoft.com/ru-ru/dotnet/csharp/programming-guide/interfaces/explicit-interface-implementation) page does not contain code samples for culture _ru-ru_,  but the boxes which should contain code samples exists. I checked that for culture **[en-us](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/interfaces/explicit-interface-implementation#feedback)** code samples are presented in the code boxes.

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: bda601c2-3dbe-4ad1-db39-670cff3b654c
* Version Independent ID: 092fce57-ea16-c7a6-c85d-f6c111eba4eb
* Content: [Руководство по программированию на C#. Явная реализация интерфейса](https://docs.microsoft.com/ru-ru/dotnet/csharp/programming-guide/interfaces/explicit-interface-implementation#feedback)
* Content Source: [docs/csharp/programming-guide/interfaces/explicit-interface-implementation.md](https://github.com/dotnet/docs.ru-ru/blob/live/docs/csharp/programming-guide/interfaces/explicit-interface-implementation.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by srvbpigh** [comment]
Hello, @palicpiotr
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by palicpiotr** [comment]
> Hello, @palicpiotr
> 
> Thank you for your feedback.
> 
> We are actively reviewing your comments and will get back to you soon.
> 
> Kind regards,
> Microsoft DOCS International Team

Thanks a lot.

**Comment by srvbpigh** [comment]
Thank you for your feedback. 

Our engineer team reviewed your suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/ru-ru/dotnet/csharp/programming-guide/interfaces/explicit-interface-implementation#feedback.  

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback. 

Kind regards, 
Microsoft DOCS International Team
