### ISSUE TITLE
There is a mistake in transltion into russian

### ISSUE THREAD

**Issue by alexmikh89** [dotnet/docs.ru-ru#264]
Available:
Правый операнд является инклюзивным концом диапазона.
Must be:
Правый операнд является эксклюзивным концом диапазона.

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: 0a25abe4-2b4e-119e-85e9-af19ed06e8c0
* Version Independent ID: 682b8c86-e49a-1d6d-8562-c9f919082bdc
* Content: [Операторы доступа к членам. Справочник по C#](https://docs.microsoft.com/ru-ru/dotnet/csharp/language-reference/operators/member-access-operators)
* Content Source: [docs/csharp/language-reference/operators/member-access-operators.md](https://github.com/dotnet/docs.ru-ru/blob/live/docs/csharp/language-reference/operators/member-access-operators.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @pkulikov
* Microsoft Alias: **wiwagn**

**Comment by srvbpigh** [comment]
Hello, @alexmikh89
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
Здравствуйте, @alexmikh89!   

Спасибо за отзыв.  

Наши лингвисты рассмотрели Ваши предложения и приняли их. Мы внедрили Ваши правки в обновленные статьи на сайте документации, опубликованные на следующих страницах: https://docs.microsoft.com/ru-ru/dotnet/csharp/language-reference/operators/member-access-operators.   

Мы очень ценим Ваш вклад в наши статьи и будем рады получить другие полезные отзывы.  

С наилучшими пожеланиями,  
Международная команда поддержки документации Майкрософт
