### ISSUE TITLE
Спасибо за статью!

### ISSUE THREAD

**Issue by Boris-creator** [dotnet/docs.ru-ru#279]
Полезный материал.
________________________

Должен указать на опечатку:
"Для определения метода new в классе ShowDetails используется модификатор ConvertibleCar. Для определения метода override в классе ShowDetails используется модификатор Minivan."
Следует читать "Для определения метода ShowDetails в классе ConvertibleCar используется модификатор new. Для определения метода ShowDetails в классе Minivan используется модификатор override."

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: 4702e20f-4482-e0ce-bf61-784d436b64d5
* Version Independent ID: c88cfd2b-fdee-64eb-c26c-4d808e82e8b6
* Content: [Руководство по программированию на C#. Использование ключевых слов Override и New](https://docs.microsoft.com/ru-ru/dotnet/csharp/programming-guide/classes-and-structs/knowing-when-to-use-override-and-new-keywords#feedback)
* Content Source: [docs/csharp/programming-guide/classes-and-structs/knowing-when-to-use-override-and-new-keywords.md](https://github.com/dotnet/docs.ru-ru/blob/live/docs/csharp/programming-guide/classes-and-structs/knowing-when-to-use-override-and-new-keywords.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by srvbpigh** [comment]
Hello, @Boris-creator
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Здравствуйте, @Boris-creator 

Благодарим Вас за отзыв. Мы рады, что работа с нашей документацией соответствует Вашим ожиданиям.  

Надеемся получить от Вас и другие полезные отзывы, которые помогут нам улучшать работу и дальше.  

С наилучшими пожеланиями,  

Международная команда поддержки документации Майкрософт
