### ISSUE TITLE
Другой вариант перевода для некоторых подразделов статьи "Основные понятия"

### ISSUE THREAD

**Issue by RedAngelD** [dotnet/docs.ru-ru#280]
Добрый день!
Предлагаю другой вариант перевода для некоторых подразделов статьи "Основные понятия". На мой взгляд, предлагаемый перевод лучше текущего и понятнее для читателя.

**Запуск приложения**
Сборка, которая имеет точку входа, называется приложением. Когда приложение запускается, создается новый домен приложения. Несколько различных моментов приложения могут существовать на одной машине одновременно, и каждый из них имеет свой собственный домен приложения.
Домен приложения позволяет изолировать приложение, выступая в качестве контейнера состояния приложения. Домен приложения действует как контейнер и управляющий для объявленных в приложении типов и используемых библиотек классов. Типы, загруженные в домены одного и того же приложения, различаются, а также экземпляры объектов не разделяются между доменами приложениями. Например, каждый домен приложения имеет копию всех статических переменных его типов, и статический конструктор конкретного типа запускается не чаще одного раза в домене приложения. Реализации свободно предоставляют политику или механизмы по созданию или разрушению доменов приложения.
Запуск приложения происходит, когда среда выполнение вызывает назначенный метод, который выступает в роли точки входа в приложение. Метод точки входа всегда называется Main и может иметь одну из следующих сигнатур: 
```
static void Main() {...}
static void Main(string[] args) {...}
static int Main() {...}
static int Main(string[] args) {...}
```
Как представлено выше, точка входа может возвращать целочисленное значение. Это возвращаемое значение используется при прекращении работы приложения.
Точка входа может иметь один формальный параметр. Параметр может иметь любое имя, но тип данных параметра обязательно должен быть string[] (строковый массив). При наличии формального параметра, среда выполнения создает и передает параметр с типом string[], содержащий аргументы командной строки параметров, указанные при запуске приложения. Аргумент типа string[] никогда не может иметь пустое значение, но может иметь длину ноль, если аргументы командной строки не указаны.
В языке C# поддерживается перегрузка методов, классы или структуры могут содержать множественное определение методов, если они объявлены с разной сигнатурой. Однако в рамках одной программы ни один класс или структура не может содержать более одного метода под названием Main, определение которого квалифицирует его как точку входа приложения. Другие перегруженные версии Main разрешены, но при условии, что они имеют более одного параметра, или их единственный параметр является отличным от типа string[].
Приложение может состоять из нескольких классов или структур. Метод Main, определение которого квалифицирует его для использования в качестве точки входа приложения, может содержать более одного из этих классов или структур. В таких случаях внешний механизм (такой как опция компилятора командной строки) должен использовать один из методов Main в качестве точки входа.
В языке C# каждый метод должен быть определен как член класса или структуры. Обычно уровень доступности объявленного метода определяется модификаторами доступа, указанными в объявлении метода, аналогично с помощью модификаторов доступа определяется уровень доступности объявленного типа. Для того, чтобы данный метод данного типа можно было вызвать из другого класса или структуры, тип (подразумевается класс или структура), а также член класса (метод) должны быть доступными. Однако точка входа приложения представляет собой особый случай. В частности, среда выполнения может получить доступ к точке входа приложения независимо от его заявленного уровня доступности и независимо от заявленного уровня доступности его объявленных типов.
Метод точки входа необязательно должен быть в общем объявлении класса.
Во всех других отношения методы, представляющие собой точку входа приложения, ведут себя как любые другие методы.

**Прекращение работы приложения**
Прекращение работы приложения возвращает контроль вызываемой среде выполнения.
Если возвращаемый тип метода, представляющего собой точку входа приложения, - целое число, то возвращаемое значение передает код состояния прекращения работы приложения. Такой код помогает вызываемой среде выполнения узнать с каким состоянием завершилась работа приложения: успешно или с ошибкой.
Если метод не имеет возвращаемого типа, то при завершении работы приложения, достигая правой фигурной скобки (}), которая завершает этот метод, или выполнение оператора возврата, у которого нет выражения, происходит передача кода состояния завершения - 0.
До прекращения работы приложения вызываются деструкторы для всех своих объектов, которые еще не были собраны сборщиком мусора, если такая очистка не была отключена (например, вызовом метода GC.SuppressFinalize).

**Участники**
Пространства имен и типы имеют участников (членов).  Члены сущности в основном доступны через использование квалифицированного имени, которое начинается со ссылки на сущность, а затем следует знак "." с последующим именем участника.
Члены типа либо объявляются при объявлении типа, либо унаследованы от базового класса. Когда тип наследуется от базового класса, все члены базового класса становятся членами производного класса, за исключением экземпляров конструкторов, деструкторов и статических конструкторов. Объявленный уровень доступности базового члена класса не контролирует, является ли участник наследуемым - наследование распространяется на любого члена, который не является экземпляром конструктора, деструктора или статического конструктора. Однако унаследованный член может быть недоступен в производном типе либо из-за его объявленной доступности, либо из-за того, что он скрыт в объявлении наследуемого класса.

С уважением, Дробязина Ангелина
---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: aff7dc35-2735-bf53-70c7-c35cd32a9c13
* Version Independent ID: f068067f-afec-ad12-deb5-6df96838423c
* Content: [Basic concepts - C# language specification](https://docs.microsoft.com/ru-ru/dotnet/csharp/language-reference/language-specification/basic-concepts#feedback)
* Content Source: [spec/basic-concepts.md](https://github.com/dotnet/csharplang.ru-ru/blob/live-sxs/spec/basic-concepts.md)
* Product: **dotnet-csharp**
* Technology: **csharp-spec**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **wiwagn**

**Comment by srvbpigh** [comment]
Hello, @RedAngelD
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Здравствуйте, @RedAngelD 

Спасибо за Ваше предложение! 

Публикации о проблемах с содержимым, обработанным с помощью машинного перевода, сейчас не принимаются. 

Мы ценим ваши отзывы и предложения, касающиеся переведенного вручную содержимого. Мы используем их для обучения подсистем машинного перевода. Со временем это позволит улучшить качество как машинного, так и ручного перевода. 

Статьи, переведенные вручную, можно отличить от статей, обработанных с помощью машинного перевода, по значению метаданных ms.translationtype, которое равно "HT" (при использовании машинного перевода — "MT") в заголовке каждого файла с содержимым. 

Большое спасибо за поддержку! 

Microsoft DOCS Global Experience Team
