### ISSUE TITLE
Fedora 29 is End Of Life

### ISSUE THREAD

**Issue by fixinggunsinair** [dotnet/docs.ru-ru#282]
https://fedoraproject.org/wiki/End_of_life

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: 7ea5d462-57ed-8efa-d9b0-24eb26b38fdf
* Version Independent ID: 50ddf6f4-7162-7a53-119d-5bb69e089ceb
* Content: [Установка .NET Core на Fedora 29 — диспетчер пакетов — .NET Core](https://docs.microsoft.com/ru-ru/dotnet/core/install/linux-package-manager-fedora29#feedback)
* Content Source: [docs/core/install/linux-package-manager-fedora29.md](https://github.com/dotnet/docs.ru-ru/blob/live/docs/core/install/linux-package-manager-fedora29.md)
* Product: **dotnet-core**
* GitHub Login: @Thraka
* Microsoft Alias: **adegeo**

**Comment by srvbpigh** [comment]
Hello, @fixinggunsinair
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @fixinggunsinair 

We truly appreciate your comment and we strive to improve your experience in docs.microsoft.com. However, we need more information in order to be able to address your feedback. Can you please provide more detailed information and clarify your comment? 

Kind regards, 

Microsoft DOCS International Team

**Comment by fixinggunsinair** [comment]
Sorry for the delay.

End Of Life means what that distribution version is not supported and deprecated.

Where's no need to keep page for unsupported distribution version. I suggest to delete it. But you can decide on your own, of course.

**Comment by Thraka** [comment]
Hello @fixinggunsinair We're pretty sure we're going to keep these old articles around for anyone who happens to need them, but we're going to work at trimming up the supporting articles to remove references to the EOL articles.

**Comment by Thraka** [comment]
We're using https://github.com/dotnet/docs/issues/17925 to track this.

**Comment by Thraka** [comment]
Sorry @CeciAc I closed this, but I don't know your workflow so I reopened it.

**Comment by CeciAc** [comment]
It's ok, @Thraka 
thanks for stepping in :)
