### ISSUE TITLE
Сочетаемость задач

### ISSUE THREAD

**Issue by DimTrdr** [dotnet/docs.ru-ru#284]
У вас все готово для завтрака в одно и то же время, за исключением тостов. Приготовление тоста — композиция асинхронной операции (поджарить хлеб) и синхронной операции (добавить масло и джем). Обновление этого кода иллюстрирует важную концепцию:
 Важно!

композиция асинхронной операции, за которой следует синхронная задача, является асинхронной операцией. Говоря иначе, если какая-либо часть операции является асинхронной, то и вся операция является асинхронной.

Подскажите, если вся операция является асинхронной
async Task&lt;Toast&gt; MakeToastWithButterAndJamAsync(int number)
{
    var toast = await ToastBreadAsync(number);
    ApplyButter(toast);
    ApplyJam(toast);
    return toast;
}
то зачем внутри async метода использовать несколько await, когда как после первого await операция будет являться асинхронной?

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: 17d27a0d-c072-8c9f-7e31-3de60bee9ae8
* Version Independent ID: e0c09794-e712-19ff-cb9f-12648d60d4f6
* Content: [Асинхронное программирование на C#](https://docs.microsoft.com/ru-ru/dotnet/csharp/programming-guide/concepts/async/#feedback)
* Content Source: [docs/csharp/programming-guide/concepts/async/index.md](https://github.com/dotnet/docs.ru-ru/blob/live/docs/csharp/programming-guide/concepts/async/index.md)
* Product: **dotnet-csharp**
* Technology: **csharp-async**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by srvbpigh** [comment]
Hello, @DimTrdr
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [dotnet/docs #18350](https://github.com/dotnet/docs/issues/18350) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
Здравствуйте, @DimTrdr!  

Благодарим Вас за участие. Ваш отзыв связан с исходной документацией.  

Поэтому мы переносим Вашу заявку в репозиторий по английскому языку. Ее состояние можно просмотреть здесь: https://github.com/dotnet/docs/issues/18350.  

Мы очень ценим Ваш вклад в наши статьи.   

С наилучшими пожеланиями,  
Международная команда поддержки документации Майкрософт

**Comment by DimTrdr** [comment]
Здравствуйте. Хорошо. Спасибо.
