### ISSUE TITLE
Замените содержимое метода Main в файле Program.cs следующим кодом: *** а где сам код ??

### ISSUE THREAD

**Issue by veretennikovalexey** [dotnet/docs.ru-ru#289]
[Введите отзыв здесь]

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: 8cc2e9c2-f333-f6a1-064e-790d950b684c
* Version Independent ID: 25a4c9b9-2808-e296-df03-5837000dcbad
* Content: [Создание консольного приложения с помощью .NET Core в Visual Studio Code - .NET Core](https://docs.microsoft.com/ru-ru/dotnet/core/tutorials/with-visual-studio-code)
* Content Source: [docs/core/tutorials/with-visual-studio-code.md](https://github.com/dotnet/docs.ru-ru/blob/live/docs/core/tutorials/with-visual-studio-code.md)
* Product: **dotnet-core**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by srvbpigh** [comment]
Здравствуйте, @veretennikovalexey.

Мы совершенствуем внутренний процесс и конвейер инжиниринга. К сожалению, это приводит к задержкам при обработке ваших отзывов.

Мы очень ценим Ваш вклад в наши статьи и то, что относитесь к ситуации с пониманием. Надеемся получать от Вас поддержку и в будущем.

**Comment by tdykstra** [comment]
This has been fixed in the English version but the fix hasn't been applied to the Russian version yet.  You can find the code here: https://docs.microsoft.com/en-us/dotnet/core/tutorials/with-visual-studio-code#enhance-the-app

**Comment by veretennikovalexey** [comment]
Thank you. I didn't think that Your answer to me so fast. I like it)
