### ISSUE TITLE
Ошибочные ссылки на странице

### ISSUE THREAD

**Issue by WiseRaccoon** [dotnet/docs.ru-ru#321]
Внизу страницу перепутаны ссылки "Установка .NET в Linux" и "Установка .NET в macOS"

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: 7f2842ce-ee53-ec35-90c6-791a952dfc3b
* Version Independent ID: 79ec96d5-9c2c-1eaa-feb8-40b0afee6a30
* Content: [Проверка установленных версий .NET в Windows, Linux и macOS — .NET](https://docs.microsoft.com/ru-ru/dotnet/core/install/how-to-detect-installed-versions)
* Content Source: [docs/core/install/how-to-detect-installed-versions.md](https://github.com/dotnet/docs.ru-ru/blob/live/docs/core/install/how-to-detect-installed-versions.md)
* Product: **dotnet-core**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
Благодарим Вас за сообщение об этой проблеме. Это было зафиксировано в PR dotnet/docs#21589. Я не знаю, сколько времени требуется для страницы, которая будет переведена, хотя. Извините!

**Comment by adegeo** [comment]
Duplicate of dotnet/docs#21588
