### ISSUE TITLE
Пропущено слово (Missing word)

### ISSUE THREAD

**Issue by anreton** [dotnet/docs.ru-ru#76]
https://docs.microsoft.com/ru-ru/dotnet/csharp/language-reference/keywords/const

"Для объявления константного поля или константной локальной используется"

->

"Для объявления константного поля или константной локальной **переменной** используется"

**Comment by nokura** [comment]
Thank you for your input. I am addressing your suggestion to our internal linguistic team. I will get back to you when the decision is made.

**Comment by MSDN-WhiteKnight** [comment]
I suggested a [commit](https://github.com/MSDN-WhiteKnight/docs.ru-ru/commit/c23599fae3a37a5e1980123e4e9a88d8adc21a01) that attempted to fix this. But it looks like it was overwrittent by later changes.

**Comment by gosali** [comment]
Hello, @MSDN-WhiteKnight @anreton ,  
  
Thank you for your feedback. 
  
Our linguistic team reviewed your linguist suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/ru-ru/dotnet/csharp/language-reference/keywords/const.  
 
We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback. 
 
Kind regards, 
Microsoft DOCS International Team
