### ISSUE TITLE
Сантиметры и дюймы

### ISSUE THREAD

**Issue by BLIZZZZARD** [dotnet/docs.ru-ru#87]
Вы должны получить ответ от 19 до 20. >> Вы должны получить ответ от 126 до 127.
необходимо перевести в сантиметры и получится 

https://docs.microsoft.com/ru-ru/dotnet/csharp/quick-starts/numbers-in-csharp-local

**Comment by nokura** [comment]
Thank you for your input. The following fix was made at 6ba5858e27a3c3eb29e37ee8b247f5f7a1117684.  Thank you for the input. I am closing this issue.
SRC: You should get an answer between 19 and 20.
TGT:Вы должны получить ответ от 19 до 20.
UPD: Вы должны получить ответ от 126 до 127.
